[project]
name = "loki"
version = "0.1.0"
description = "The LLM pipeline, implemented from scratch."
requires-python = ">=3.12"
dependencies = [
    "torch>=2.4",
    "numpy",
    "matplotlib",
    "graphviz",
    "regex",
    "tiktoken",
    "requests",
    "tqdm",
]

[dependency-groups]
dev = [
    "jupyter",
    "pytest",
]
